### ISSUE TITLE
Postcss autoprefixer is not working for me

### ISSUE THREAD

**Issue by jitendravyas** [acss-io/webpack-atomizer-loader#16]
https://github.com/acss-io/webpack-atomizer-loader#postcss-plugins

```
 error  in ./src/components/Sidenav.vue

Module build failed: TypeError: Cannot read property 'postcss' of null
    at Processor.normalize (/Users/jitendravyas/wcore/component-ui/node_modules/postcss/lib/processor.js:137:12)
    at new Processor (/Users/jitendravyas/wcore/component-ui/node_modules/postcss/lib/processor.js:51:25)
    at postcss (/Users/jitendravyas/wcore/component-ui/node_modules/postcss/lib/postcss.js:73:10)
    at /Users/jitendravyas/wcore/component-ui/node_modules/webpack-atomizer-loader/dist/atomicLoader.js:107:46
    at parseAndGenerateFile (/Users/jitendravyas/wcore/component-ui/node_modules/webpack-atomizer-loader/dist/atomicLoader.js:80:12)
    at /Users/jitendravyas/wcore/component-ui/node_modules/webpack-atomizer-loader/dist/atomicLoader.js:147:16
    at Array.map (native)
    at Object.atomicLoader (/Users/jitendravyas/wcore/component-ui/node_modules/webpack-atomizer-loader/dist/atomicLoader.js:146:29)
```

```
       test: /\.vue$/,
        use: [
          {
            loader: 'vue-loader',
            options: vueLoaderConfig
          },
          {
            loader: 'webpack-atomizer-loader',
            query: {
              postcssPlugins: [ require('autoprefixer') ],
              configPath: path.resolve('atomCssConfig.js')
            }
          }
```

**Comment by redonkulus** [comment]
We recently updated all the dependencies, please try it again and re-open if still an issue.
