### ISSUE TITLE
Atomic CSS not in production Webpack 4 build

### ISSUE THREAD

**Issue by daynewright** [acss-io/webpack-atomizer-loader#22]
I am not sure if this is a `webpack-atomizer-loader` issue but I am not getting all of my atomic css added on a `production` build using Webpack 4.  It works perfectly with `development`.

Atomic file is on the left and Webpack css is on the right:
![screen shot 2018-07-27 at 8 48 04 pm](https://user-images.githubusercontent.com/5472982/43351856-6a8b835e-91de-11e8-8a80-6556cbe7e823.png)

```
      {
        test: /\.jsx?$/,
        exclude: /(node_modules)/,
        use: [
          {
            loader: 'webpack-atomizer-loader',
            query: {
              postcssPlugins: [autoprefixer],
              configPath: path.resolve('./atomizerConfig.js')
            }
          },
          {
            loader: 'babel-loader',
            options: {}
          }
        ]
      }
```

**Comment by tom76kimo** [comment]
I simply test it and see no problem with my generated css file. This is my test webpack config FYR
```js
module.exports = {
    mode: 'production',
    entry: __dirname + '/index.js',
    output: {
        path: __dirname,
        filename: 'bundle.js',
    },
    module: {
        rules: [
            {
                test: /\.jsx?$/,
                use: {
                    loader: 'webpack-atomizer-loader',
                    options: {
                        configPath: [path.resolve('./atomCssConfig.js')],
                    },
                },
            },
            {
                test: /\.jsx?$/,
                use: {
                    loader: 'babel-loader',
                    options: { presets: ['react', 'babel-preset-env'] },
                },
            },
        ],
    },
}
```

**Comment by daynewright** [comment]
Thanks! I have the same structure.  Everything works perfectly fine for `webpack-dev-server` but when using `webpack` in either production or development mode returns the same results of losing parts of the atomic SCSS file.  I wonder if webpack does a dedupe and it is removing some of the classes that seem to match.

**Comment by tom76kimo** [comment]
I use `webpack` not `webpack-dev-server`, looks no issue for me.

**Comment by daynewright** [comment]
Well.. I thought that fixed it but I am still getting this issue on the build.  I have attempted multiple builds on the same webpack structure and some times it works and sometimes it does not.
Could this error with `parseQuery` be the issue for webpack-atomizer?

```
(node:98677) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at parseQuery (/Users/dwright/Desktop/*****/node_modules/loader-utils/index.js:78:3)
    at Object.atomicLoader (/Users/dwright/Desktop/*****/node_modules/webpack-atomizer-loader/dist/atomicLoader.js:68:45)
    at LOADER_EXECUTION (/Users/dwright/Desktop/*****/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/dwright/Desktop/*****/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/dwright/Desktop/*****/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at iterateNormalLoaders (/Users/dwright/Desktop/*****/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/dwright/Desktop/*****/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at Object.context.callback (/Users/dwright/Desktop/LIFEWAY_PROJECTS/CSRT/commerce-csrt_frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.module.exports (/Users/dwright/Desktop/*****/node_modules/babel-loader/lib/index.js:182:8)
    at LOADER_EXECUTION (/Users/dwright/Desktop/*****/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/dwright/Desktop/*****/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/dwright/Desktop/*****/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/dwright/Desktop/*****/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/dwright/Desktop/*****/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/dwright/Desktop/*****/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/dwright/Desktop/*****/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```
